# Generated by Django 5.1.2 on 2025-02-05 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Axie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axie_id', models.CharField(max_length=50, unique=True)),
                ('breed_count', models.IntegerField()),
                ('axie_class', models.CharField(max_length=20)),
                ('cards', models.TextField(help_text='Enter the cards separated by comma')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('sell_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Owned', 'Owned'), ('Listed', 'Listed'), ('Sold', 'Sold')], default='Owned', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField()),
                ('axie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.axie')),
            ],
        ),
    ]
