# Generated by Django 5.1.2 on 2025-02-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='axie',
            name='axie_class',
        ),
        migrations.RemoveField(
            model_name='axie',
            name='cards',
        ),
        migrations.AlterField(
            model_name='axie',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
