# Generated by Django 5.1.2 on 2025-02-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_amount_transaction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axie',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
